### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by siegfriedbe** [alex47exe/AutoUWP-Launcher#1]
well, the program gets detected as Trojan:Win32/Occamy.c by windows defender and as a bitcoin miner with malwarebytes

**Comment by alex47exe** [comment]
False positive due to the developer features executables (compiled bat files, using Bat 2 Exe Converter v3.0.10). You can compile them yourself with admin privileges and no gui, then compile the main script with AutoIt. You'll see that you get the same false positives.

**Comment by siegfriedbe** [comment]
oh ok
